import { Form } from 'react-router-dom'

export {default as Main} from './Main'
export {default as Navbar} from './Navbar'
export {default as Home} from './Home'
export {default as Login} from './Login'
export {default as Register} from './Register'
export {default as AllActivities} from './AllActivities'
export {default as AllRoutines} from './AllRoutines'
export {default as MyRoutines} from './MyRoutines'
export {default as SeeActivities} from './SeeActivities'
export {default as DetailButton} from './DetailButton'
export {default as EditButton} from './EditButton'
export {default as EditRoutine} from './EditRoutine'
export {default as DeleteButton} from './DeleteButton'
export {default as DeleteActivityButton} from './DeleteActivityButton'
